name: Qt Project Auto Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  qt-build-check:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodları GitHub serverinə yükləyir
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Virtual serverdə Qt 6 mühitini hazırlayır
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'

    # 3. Layihənin qmake və make ilə xətasız yığılmasını yoxlayır
    - name: Compile Project
      run: |
        qmake
        make
