name: Qt Project Auto Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  qt-build-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'

    - name: Compile Project
      run: |
        qmake
        make
